[package]
name = "webidl2wit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0"
heck = "0.5"
itertools = "0.13"
# need https://github.com/rustwasm/weedle/pull/56
weedle = { git = "https://github.com/rustwasm/weedle.git" }
wit-encoder = { git = "https://github.com/bytecodealliance/wasm-tools.git", branch = "wit-encoder-use" }

[dev-dependencies]
pretty_assertions = "1.4.0"
